repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: fix-encoding-pragma
        args: ["--remove"]
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore
    -   id: python-use-type-annotations
    -   id: python-check-mock-methods
    -   id: python-no-log-warn
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal
    -   id: text-unicode-replacement-char
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies: ["flake8-bugbear==21.4.3"]
