language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pypoetry

matrix:
    include:
        - python: 2.7
          env: {TOX_ENV: py27}
        - python: 3.5
          env: {TOX_ENV: py35}
        - python: 3.6
          env: {TOX_ENV: py36, COVERAGE: 1}
        - python: 3.6
          env: {TOX_ENV: flake8}

before_install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -

install:
    - poetry install -v

script:
    - tox -e $TOX_ENV

after_success:
    - "[ ! -z $COVERAGE ] && bash <(curl -s https://codecov.io/bash) || true"
